### ISSUE TITLE
Brief

### ISSUE THREAD

**Issue by fpersyn** [Birkbeck/sdp23-coursework-fpersyn#2]
### SML instructions
- [x] `add r s` – (1) add the contents of registers `r` and `s`; (2) store the results in register `r`;
- [x] `sub r s` – (1) subtract the contents of registers `s` from `r`; (2) store the results in register `r`;
- [x] `mul r s` – (1) multiply the contents of registers `r` and `s`; (2) store the results in register `r`;
- [x] `div r s` – (1) integer divide contents of registers `r` by `s`; (2) store the results in register `r`;
- [x] `out s` – print the contents of register `s` on the console
- [x] `mov r x` – store integer `x` in register `r`
- [x] `jnz s L` – if contents of register `s` is not zero, make the statement labeled `L` the next statement to execute.

Where `L` is a label – no 2 instructions can have the same label.

### Example SML program

Compute the factorial of 6:
```
mov EAX 6
mov EBX 1
mov ECX 1
f3: mul EBX EAX
sub EAX ECX
jnz EAX f3
out EBX
```

Properties
- Labels end with a colon which is not part of it – for example `f3`
- Fields of an instruction are separated by whitespace
- Instructions of a program are executed in order, unless the order is changed by execution of a `jnz` instruction
- Execution of program terminates when its last instruction has been execute (and it doesn’t change the order of exec)

### Interpreter requirements

- [x] Read the name of a file that contains the program from the command line (via `String[] args` and `Main` class)
- [x] Read the program from the file and translate it into the internal form
- [x] Print the program out
- [x] Execute the program
- [x] Print the final values of the registers

### Getting started

* Provided with boilerplate so you can focus on program execution part
* Examine the `Machine` class first – heart of the program
* Look at the fields of `Machine` – contains what is needed to execute an SML program: labels, program (internal form), registers, program counter (index of next instruction to exec). Array-like structures used (no size limit on SML program), map used for registers and labels (access by name).
* Next, look at `Machine.execute` – executes the program using a fetch-decode-execute cycle. At iteration: instruction fetched, counter incremented, and executed – `jnz` has ability to change counter.
* `Translator` contains methods that read the program and translate. ⚠️ WARNING – few tests here.
* Finally, study `main` method in `Main` class.

### Tasks

All programming required has to do with the `Instruction` class and its subclasses. The class is abstract (shouldn’t be instantiated) forcing every subclass to implement it. Every instruction has an optional label and operation – common to every instruction – hence properties maintained in instruction base class.

**PART1**
- [ ] 0. All of these parts of the coursework should be fully tested (you do not need to provide tests for the original codebase).
- [x] 1. Complete methods in `Instruction` class – may require new fields, make sure they are protected (accessible in subclasses)
- [x] 2. Create a subclass of `Instruction` for each kind of SML instruction + fix the method `Translator.instruction` so that it properly translates that kind of instruction.  
- HINT1: write one instruction at a time and test it out thoroughly, before proceeding to the next!
- HINT2: Start with the add instruction, because the code for translating it is already there — in method Translator.instruction . Initially, the program will not compile because there is no class for the instruction add ; once that class is written, the program will compile.
- [x] 2.1 `add r s` – (1) add the contents of registers `r` and `s`; (2) store the results in register `r`;
- [x] 2.2 `sub r s` – (1) subtract the contents of registers `s` from `r`; (2) store the results in register `r`;
- [x] 2.3 `mul r s` – (1) multiply the contents of registers `r` and `s`; (2) store the results in register `r`;
- [x] 2.4 `div r s` – (1) integer divide contents of registers `r` by `s`; (2) store the results in register `r`;
- [x] 2.5 `out s` – print the contents of register `s` on the console
- [x] 2.6`mov r x` – store integer `x` in register `r`
- [x] 2.7 `jnz s L` – if contents of register `s` is not zero, make the statement labeled `L` the next statement to execute.
- [x] 4. For each instruction, the subclass needs appropriate fields, a constructor, `toString` method, and a method `execute` ; toString and execute should override the same methods in the Instruction class using appropriate annotations.
- [x] 5. As you do this, you will see that each successive class can be written by duplicating a previous one and modifying it (obviously avoiding too much repeated code).
- [x] 6. After you finish writing a subclass for an SML instruction (except for `add` ), you will have to add code to the method `Translator.instruction` to translate that instruction. The existing code for translating add should help you with this.
- [x] 7. There are also a few places in the code with TODO: labels - follow the instructions to improve the provided code (or implement missing methods as required). 
- [x] 8. Use the Java Stream API whenever possible instead of loops.

**PART2**
- [x] 9. Apart from the specific requests above/below you should not modify other classes.
- [x] 10. Next, take the `switch` statement that decides which type of instruction is created and modify the code so that it uses reflection to create the instances, i.e., remove the explicit calls to the subclasses and the `switch` statement. This will allow the SML language to be extended without having to modify the original code.
- [x] 11. Modify the source code to use dependency injection
- [x] 12.  Modify the source code to use the singleton design pattern, where you deem appropriate.
- [x] 13.  Modify the source code to use factory classes, where you deem appropriate.
- [x] 14. You are allowed to use other design patterns if you consider them necessary.

**Comment by fpersyn** [comment]
Regarding:

11 - dependency injection ––> Use [Google Dagger](https://dagger.dev) – want to avoid getting stuck wrapping my head around Spring’s XML

**Comment by fpersyn** [comment]
- :question: QUESTION: Are all instructions immutable value objects? Shouldn’t we then implement them all using a dataclass (e.g. record)?

**Comment by fpersyn** [comment]
Reflection: https://www.oracle.com/technical-resources/articles/java/javareflection.html
